// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starbucks.Persistence;

#nullable disable

namespace Starbucks.Persistence.Migrations
{
    [DbContext(typeof(StarbucksDbContext))]
    [Migration("20260728043920_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Starbucks.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IceCoffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HotCoffee"
                        });
                });

            modelBuilder.Entity("Starbucks.Domain.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("Starbucks.Domain.CoffeeIngredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoffeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId", "CoffeeId");

                    b.HasIndex("CoffeeId");

                    b.ToTable("CoffeeIngredient");
                });

            modelBuilder.Entity("Starbucks.Domain.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Starbucks.Domain.Coffee", b =>
                {
                    b.HasOne("Starbucks.Domain.Category", "Category")
                        .WithMany("Coffees")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Starbucks.Domain.CoffeeIngredient", b =>
                {
                    b.HasOne("Starbucks.Domain.Coffee", "Coffee")
                        .WithMany("CoffeeIngredients")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Starbucks.Domain.Ingredient", "Ingredient")
                        .WithMany("CoffeeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Starbucks.Domain.Category", b =>
                {
                    b.Navigation("Coffees");
                });

            modelBuilder.Entity("Starbucks.Domain.Coffee", b =>
                {
                    b.Navigation("CoffeeIngredients");
                });

            modelBuilder.Entity("Starbucks.Domain.Ingredient", b =>
                {
                    b.Navigation("CoffeeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
